const MoviesActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_MOVIES_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_MOVIES_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_MOVIES_COLLECTIONS_FAILURE',
    UPDATE_SEARCH_FILTER: 'UPDATE_SEARCH_FILTER',
};

export default MoviesActionTypes;